import Head from 'next/head'
import Menu from '../components/menu/Menu'
import Scan from '../components/scan/Scan'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl text-green-500 font-bold ">
      Inward Page
    </h1>
        <Menu />
        <Scan />
    </div>
  )
}
